{
 "title": "env-sensor-app-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latest Reading per Sensor ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (zone, telemetry_name)\r\n  zone,\r\n  telemetry_name,\r\n  value,\r\n  timestamp,\r\n  CASE\r\n    WHEN timestamp < now() - interval '20 minutes' THEN 'Offline'\r\n    ELSE 'OK'\r\n  END AS status\r\nFROM sensor_data\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY zone, telemetry_name, timestamp DESC\r\n"
    }
   ]
  },
  {
   "title": "Zone heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', timestamp) AS time,\r\n  zone AS metric,\r\n  value\r\nFROM sensor_data\r\nWHERE telemetry_name = 'temperature'\r\nORDER BY time, zone"
    }
   ]
  },
  {
   "title": "Zone pressure map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', timestamp) AS time,\r\n  zone AS metric,\r\n  value\r\nFROM sensor_data\r\nWHERE telemetry_name = 'pressure'\r\nORDER BY time, zone"
    }
   ]
  },
  {
   "title": "Zone humidity map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', timestamp) AS time,\r\n  zone AS metric,\r\n  value\r\nFROM sensor_data\r\nWHERE telemetry_name = 'humidity'\r\nORDER BY time, zone"
    }
   ]
  },
  {
   "title": "Readings per Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(timestamp, $__interval),\r\n  zone,\r\n  COUNT(*) as readings\r\nFROM sensor_data\r\nGROUP BY 1, zone\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Min/Max/Avg per Zone",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  zone,\r\n  telemetry_name,\r\n  min(value) as min,\r\n  max(value) as max,\r\n  avg(value) as avg\r\nFROM sensor_data\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY zone, telemetry_name"
    }
   ]
  },
  {
   "title": "Recent Readings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, COUNT(*) AS count\r\nFROM sensor_data\r\nGROUP BY timestamp\r\nORDER BY timestamp DESC;\r\n"
    }
   ]
  },
  {
   "title": "Zone A readings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', timestamp) AS \"time\",\r\n  telemetry_name AS \"metric\",\r\n  avg(value) AS \"value\"\r\nFROM\r\n  sensor_data\r\nWHERE\r\n  zone = 'ZoneA'\r\nGROUP BY\r\n  \"time\",\r\n  \"metric\"\r\nORDER BY\r\n  \"time\""
    }
   ]
  },
  {
   "title": "Zone B Readings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', timestamp) AS \"time\",\r\n  telemetry_name AS \"metric\",\r\n  avg(value) AS \"value\"\r\nFROM\r\n  sensor_data\r\nWHERE\r\n  zone = 'ZoneB'\r\nGROUP BY\r\n  \"time\",\r\n  \"metric\"\r\nORDER BY\r\n  \"time\""
    }
   ]
  },
  {
   "title": "Zone C Readings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', timestamp) AS \"time\",\r\n  telemetry_name AS \"metric\",\r\n  avg(value) AS \"value\"\r\nFROM\r\n  sensor_data\r\nWHERE\r\n  zone = 'ZoneC'\r\nGROUP BY\r\n  \"time\",\r\n  \"metric\"\r\nORDER BY\r\n  \"time\""
    }
   ]
  }
 ]
}